# Generated by Django 5.1.3 on 2025-11-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Короткое имя в URL, латиница, дефисы. Например: drip-and-drift.",
                        max_length=80,
                        unique=True,
                        verbose_name="URL-ярлык",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Название кофейни"),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Короткое описание"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Москва", max_length=80, verbose_name="Город"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Например: Центр, Юг, Таганка.",
                        max_length=80,
                        verbose_name="Район / часть города",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("$", "Бюджетно"),
                            ("$$", "Средний чек"),
                            ("$$$", "Дороже среднего"),
                        ],
                        default="$$",
                        max_length=3,
                        verbose_name="Уровень цен",
                    ),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=True, verbose_name="Есть Wi-Fi"),
                ),
                (
                    "has_food",
                    models.BooleanField(
                        default=True, verbose_name="Есть еда / десерты"
                    ),
                ),
                (
                    "features",
                    models.CharField(
                        blank=True,
                        help_text="Например: фильтр, V60, десерты, много розеток.",
                        max_length=200,
                        verbose_name="Особенности",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "is_open_now",
                    models.BooleanField(
                        default=True,
                        help_text="Пока ставим руками, потом можно будет считать по расписанию.",
                        verbose_name="Открыто сейчас (заглушка)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Кофейня",
                "verbose_name_plural": "Кофейни",
                "ordering": ["-rating", "name"],
            },
        ),
    ]
