# Generated by Django 5.1.3 on 2025-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Пара абзацев о месте: атмосфера, формат, для кого.",
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Фото, которое будет на карточке и вверху страницы кофейни.",
                null=True,
                upload_to="cafes/main/",
                verbose_name="Основное фото",
            ),
        ),
    ]
